/*
 *  Tekijä: Jari Hiltunen, Hanko, Finland.
 *  Location: KO19LU (maidenhead).
 *  Free to reuse/distribute with written permission by the author.
 */
package ruokapaivakirja;

/**
 * Aloitussivu, joka kokoaa yhteen tiedot. Tästä haaraudutaan eteenpäin.
 * Tekijä:     @author Jari Hiltunen
 * Versio:     @version 1.0a
 * SDK alkaen: @since 8.0.73
 */
import static ruokapaivakirja.Ruokapaivakirja.henkilot;
import static ruokapaivakirja.Ruokapaivakirja.henkilotietokanta;
import java.util.*;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static ruokapaivakirja.Ruokapaivakirja.tapahtumat;
import static ruokapaivakirja.Ruokapaivakirja.tapahtumatietokanta;
import static ruokapaivakirja.Ruokapaivakirja.tuotetietokanta;
import static ruokapaivakirja.Ruokapaivakirja.tuotteet;
/** Yhteenvetosivu kokoaa syötetyt tiedot yhteen ja tekee laskelmia. */
public class Yhteenveto extends javax.swing.JFrame {
// globaalit //    
public static String nimiApu;
public static Integer henkiloNumeroApu;


    /**
     * Creates new form Yhteenveto
     */
    public Yhteenveto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelToteutumaYhtVeto = new javax.swing.JPanel();
        labelEnsimmainenPunnitusvm = new javax.swing.JLabel();
        txtEnsimmainenPunnitusPvm = new javax.swing.JTextField();
        labelViimeisinPunnitusPvm = new javax.swing.JLabel();
        txtViimeisinPunnitusPvm = new javax.swing.JTextField();
        labelEnnsutePainoAlennus = new javax.swing.JLabel();
        labelMitattuPainoEdellinen = new javax.swing.JLabel();
        txtEdellinenMitattuPaino = new javax.swing.JTextField();
        labelPainoEro = new javax.swing.JLabel();
        txtPainoEro = new javax.swing.JTextField();
        txtEnnustePainonAlentuminen = new javax.swing.JTextField();
        scrollYhteenveto = new javax.swing.JScrollPane();
        listaEnitenSyodyt = new javax.swing.JList<>();
        labelEnnustepaino = new javax.swing.JLabel();
        txtEnnustePaino = new javax.swing.JTextField();
        panelHenkiloValinta = new javax.swing.JPanel();
        comboValitseHenkilo = new javax.swing.JComboBox<>();
        labelIka = new javax.swing.JLabel();
        labelPaino = new javax.swing.JLabel();
        labelPituus = new javax.swing.JLabel();
        labelHuomautus = new javax.swing.JLabel();
        textIka = new javax.swing.JTextField();
        textPaino = new javax.swing.JTextField();
        textPituus = new javax.swing.JTextField();
        textHuomautus = new javax.swing.JTextField();
        labelLaskennalliset = new javax.swing.JLabel();
        labelBMR = new javax.swing.JLabel();
        textBMR = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textYhteensaEnergia = new javax.swing.JTextField();
        labelEnergiaTapahtumiaYht = new javax.swing.JLabel();
        txtEnergiaTapahtumiaYhteensa = new javax.swing.JTextField();
        labelEnergiaPaiva = new javax.swing.JLabel();
        txtEnergiaPaiviaKulunut = new javax.swing.JTextField();
        paneeliEnergiaLaskuri = new javax.swing.JPanel();
        labelEnergiaEdellinenVRK = new javax.swing.JLabel();
        labelEnergiaKaikkiYhteensa = new javax.swing.JLabel();
        txtEnergiaEdVrk = new javax.swing.JTextField();
        txtEnergiaKaikkiYht = new javax.swing.JTextField();
        labelProteiinia = new javax.swing.JLabel();
        labelKCALSyoty = new javax.swing.JLabel();
        textProtEdVrk = new javax.swing.JTextField();
        labelHiilaria = new javax.swing.JLabel();
        labelRasvaa = new javax.swing.JLabel();
        txtHHVrk = new javax.swing.JTextField();
        txtRasvaVrk = new javax.swing.JTextField();
        txtProtYht = new javax.swing.JTextField();
        txtHHYht = new javax.swing.JTextField();
        txtRasvaYht = new javax.swing.JTextField();
        labelKeskimPaiva = new javax.swing.JLabel();
        txtEnergiaKeskimPaiva = new javax.swing.JTextField();
        txtProtKeskimPaiva = new javax.swing.JTextField();
        txtHHKeskimPaiva = new javax.swing.JTextField();
        txtRasvaKeskimPaiva = new javax.swing.JTextField();
        labelEnnusteEnergiaKok = new javax.swing.JLabel();
        txtEnnusteEnergiaKok = new javax.swing.JTextField();
        toolBarYhteenVeto = new javax.swing.JToolBar();
        buttonLopeta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        buttonHenkilotiedot = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        buttonTuoteTiedot = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        buttonPaivakirja = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ruokapäiväkirja - Yhteenveto (c) 2016 Jari Hiltunen");
        setName("YhteenVetoKehys"); // NOI18N

        panelToteutumaYhtVeto.setBackground(new java.awt.Color(204, 255, 204));
        panelToteutumaYhtVeto.setBorder(javax.swing.BorderFactory.createTitledBorder("Yhteenveto"));
        panelToteutumaYhtVeto.setForeground(new java.awt.Color(255, 204, 204));

        labelEnsimmainenPunnitusvm.setText("Ensimmäinen punnituspäivämäärä");

        txtEnsimmainenPunnitusPvm.setEditable(false);

        labelViimeisinPunnitusPvm.setText("Viimeisin punnituspäivämäärä");

        txtViimeisinPunnitusPvm.setEditable(false);

        labelEnnsutePainoAlennus.setText("Ennustepainonalennus kg");

        labelMitattuPainoEdellinen.setText("Edellinen mitattu paino");

        txtEdellinenMitattuPaino.setEditable(false);

        labelPainoEro.setText("Painoero (alkupaino-edellinen mittaus)");

        txtPainoEro.setEditable(false);
        txtPainoEro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPainoEroActionPerformed(evt);
            }
        });

        txtEnnustePainonAlentuminen.setEditable(false);

        listaEnitenSyodyt.setBorder(javax.swing.BorderFactory.createTitledBorder("Eniten olet saanut energiaa syömällä näitä tuotteita"));
        listaEnitenSyodyt.setModel(new javax.swing.AbstractListModel<String>() {
            String strings[] = enitenEnergiaa();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaEnitenSyodyt.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scrollYhteenveto.setViewportView(listaEnitenSyodyt);

        labelEnnustepaino.setText("Ennustepaino kg");

        txtEnnustePaino.setEditable(false);

        javax.swing.GroupLayout panelToteutumaYhtVetoLayout = new javax.swing.GroupLayout(panelToteutumaYhtVeto);
        panelToteutumaYhtVeto.setLayout(panelToteutumaYhtVetoLayout);
        panelToteutumaYhtVetoLayout.setHorizontalGroup(
            panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToteutumaYhtVetoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEnsimmainenPunnitusvm)
                    .addComponent(labelViimeisinPunnitusPvm)
                    .addComponent(labelMitattuPainoEdellinen)
                    .addComponent(labelPainoEro)
                    .addComponent(labelEnnsutePainoAlennus)
                    .addComponent(labelEnnustepaino))
                .addGap(28, 28, 28)
                .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEnsimmainenPunnitusPvm, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addComponent(txtViimeisinPunnitusPvm))
                    .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtEnnustePaino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                        .addComponent(txtEnnustePainonAlentuminen, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPainoEro, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEdellinenMitattuPaino, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollYhteenveto, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelToteutumaYhtVetoLayout.setVerticalGroup(
            panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelToteutumaYhtVetoLayout.createSequentialGroup()
                .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelToteutumaYhtVetoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEnsimmainenPunnitusvm)
                            .addComponent(txtEnsimmainenPunnitusPvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelViimeisinPunnitusPvm)
                            .addComponent(txtViimeisinPunnitusPvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdellinenMitattuPaino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMitattuPainoEdellinen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPainoEro)
                            .addComponent(txtPainoEro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnnsutePainoAlennus)
                            .addComponent(txtEnnustePainonAlentuminen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelToteutumaYhtVetoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelToteutumaYhtVetoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelEnnustepaino))
                            .addGroup(panelToteutumaYhtVetoLayout.createSequentialGroup()
                                .addComponent(txtEnnustePaino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(scrollYhteenveto))
                .addContainerGap())
        );

        panelHenkiloValinta.setBackground(new java.awt.Color(255, 255, 204));
        panelHenkiloValinta.setBorder(javax.swing.BorderFactory.createTitledBorder("Henkilövalinta"));

        comboValitseHenkilo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        comboValitseHenkilo.setModel(new javax.swing.DefaultComboBoxModel<>(listaaHenkiloNimet()));
        comboValitseHenkilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboValitseHenkiloActionPerformed(evt);
            }
        });

        labelIka.setText("Ikä");

        labelPaino.setText("Alkupaino");

        labelPituus.setText("Pituus");

        labelHuomautus.setText("Huomautus");

        textIka.setEditable(false);

        textPaino.setEditable(false);

        textPituus.setEditable(false);

        textHuomautus.setEditable(false);
        textHuomautus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHuomautusActionPerformed(evt);
            }
        });

        labelLaskennalliset.setText("Laskennalliset energia-arviot kcal/vrk");

        labelBMR.setText("BMR (peruskulutus)");

        textBMR.setEditable(false);

        jLabel1.setText("Yhteensä kulutus");

        textYhteensaEnergia.setEditable(false);

        labelEnergiaTapahtumiaYht.setText("Tapahtumia yhteensä");

        txtEnergiaTapahtumiaYhteensa.setEditable(false);

        labelEnergiaPaiva.setText("Päiviä kulunut");

        txtEnergiaPaiviaKulunut.setEditable(false);

        javax.swing.GroupLayout panelHenkiloValintaLayout = new javax.swing.GroupLayout(panelHenkiloValinta);
        panelHenkiloValinta.setLayout(panelHenkiloValintaLayout);
        panelHenkiloValintaLayout.setHorizontalGroup(
            panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHenkiloValintaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboValitseHenkilo, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHenkiloValintaLayout.createSequentialGroup()
                                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIka)
                                    .addComponent(labelPaino)
                                    .addComponent(labelPituus)
                                    .addComponent(labelHuomautus))
                                .addGap(15, 15, 15)
                                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHuomautus, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(textIka, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                        .addComponent(textPaino, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textPituus, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelLaskennalliset, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHenkiloValintaLayout.createSequentialGroup()
                                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelBMR)
                                    .addComponent(jLabel1))
                                .addGap(4, 4, Short.MAX_VALUE)
                                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textYhteensaEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textBMR, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelHenkiloValintaLayout.createSequentialGroup()
                        .addComponent(labelEnergiaTapahtumiaYht)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnergiaTapahtumiaYhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelEnergiaPaiva)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnergiaPaiviaKulunut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelHenkiloValintaLayout.setVerticalGroup(
            panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHenkiloValintaLayout.createSequentialGroup()
                .addComponent(comboValitseHenkilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIka)
                    .addComponent(textIka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLaskennalliset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPaino)
                    .addComponent(textPaino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBMR)
                    .addComponent(textBMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPituus)
                    .addComponent(textPituus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(textYhteensaEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHuomautus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHuomautus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelHenkiloValintaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnergiaTapahtumiaYht)
                    .addComponent(txtEnergiaTapahtumiaYhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnergiaPaiva)
                    .addComponent(txtEnergiaPaiviaKulunut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        paneeliEnergiaLaskuri.setBackground(new java.awt.Color(255, 204, 204));
        paneeliEnergiaLaskuri.setBorder(javax.swing.BorderFactory.createTitledBorder("Energialaskenta"));

        labelEnergiaEdellinenVRK.setText("Edellinen vuorokausi");

        labelEnergiaKaikkiYhteensa.setText("Kaikki yhteensä");

        txtEnergiaEdVrk.setEditable(false);

        txtEnergiaKaikkiYht.setEditable(false);

        labelProteiinia.setText("Proteiinia/g");

        labelKCALSyoty.setText("KCAL syöty:");

        textProtEdVrk.setEditable(false);

        labelHiilaria.setText("Hiilaria/g");

        labelRasvaa.setText("Rasvaa/g");

        txtHHVrk.setEditable(false);

        txtRasvaVrk.setEditable(false);

        txtProtYht.setEditable(false);

        txtHHYht.setEditable(false);

        txtRasvaYht.setEditable(false);

        labelKeskimPaiva.setText("Keskimäärin/päivä");

        txtEnergiaKeskimPaiva.setEditable(false);

        txtProtKeskimPaiva.setEditable(false);

        txtHHKeskimPaiva.setEditable(false);

        txtRasvaKeskimPaiva.setEditable(false);

        labelEnnusteEnergiaKok.setText("Ennuste-energia yhteensä");

        txtEnnusteEnergiaKok.setEditable(false);

        javax.swing.GroupLayout paneeliEnergiaLaskuriLayout = new javax.swing.GroupLayout(paneeliEnergiaLaskuri);
        paneeliEnergiaLaskuri.setLayout(paneeliEnergiaLaskuriLayout);
        paneeliEnergiaLaskuriLayout.setHorizontalGroup(
            paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                        .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelEnergiaEdellinenVRK)
                                    .addComponent(labelEnergiaKaikkiYhteensa))
                                .addGap(18, 18, 18)
                                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnergiaKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnergiaEdVrk, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEnergiaKaikkiYht, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelKCALSyoty))
                        .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtHHKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelHiilaria)
                                        .addComponent(txtHHVrk, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textProtEdVrk, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProtKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProteiinia)
                                    .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                        .addComponent(txtProtYht, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtHHYht, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtEnnusteEnergiaKok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRasvaa)
                                    .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtRasvaKeskimPaiva, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRasvaVrk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneeliEnergiaLaskuriLayout.createSequentialGroup()
                                .addComponent(txtRasvaYht, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                        .addComponent(labelKeskimPaiva)
                        .addContainerGap())
                    .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                        .addComponent(labelEnnusteEnergiaKok)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        paneeliEnergiaLaskuriLayout.setVerticalGroup(
            paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneeliEnergiaLaskuriLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProteiinia)
                            .addComponent(labelHiilaria)
                            .addComponent(labelRasvaa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneeliEnergiaLaskuriLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelKCALSyoty)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnergiaEdellinenVRK)
                    .addComponent(txtEnergiaEdVrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProtEdVrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHHVrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRasvaVrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKeskimPaiva)
                    .addComponent(txtEnergiaKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProtKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHHKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRasvaKeskimPaiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnergiaKaikkiYht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProtYht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHHYht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRasvaYht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnergiaKaikkiYhteensa))
                .addGap(18, 18, 18)
                .addGroup(paneeliEnergiaLaskuriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnnusteEnergiaKok)
                    .addComponent(txtEnnusteEnergiaKok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        toolBarYhteenVeto.setRollover(true);

        buttonLopeta.setText("LOPETA");
        buttonLopeta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonLopeta.setFocusable(false);
        buttonLopeta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLopeta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLopeta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLopetaMouseClicked(evt);
            }
        });
        toolBarYhteenVeto.add(buttonLopeta);
        toolBarYhteenVeto.add(jSeparator1);

        buttonHenkilotiedot.setText("HENKILÖTIEDOT");
        buttonHenkilotiedot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonHenkilotiedot.setFocusable(false);
        buttonHenkilotiedot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonHenkilotiedot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonHenkilotiedot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHenkilotiedotMouseClicked(evt);
            }
        });
        toolBarYhteenVeto.add(buttonHenkilotiedot);
        toolBarYhteenVeto.add(jSeparator4);

        buttonTuoteTiedot.setText("TUOTETIEDOT");
        buttonTuoteTiedot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonTuoteTiedot.setFocusable(false);
        buttonTuoteTiedot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonTuoteTiedot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonTuoteTiedot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTuoteTiedotMouseClicked(evt);
            }
        });
        toolBarYhteenVeto.add(buttonTuoteTiedot);
        toolBarYhteenVeto.add(jSeparator3);

        buttonPaivakirja.setText("PÄIVÄKIRJA");
        buttonPaivakirja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonPaivakirja.setFocusable(false);
        buttonPaivakirja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonPaivakirja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonPaivakirja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPaivakirjaMouseClicked(evt);
            }
        });
        toolBarYhteenVeto.add(buttonPaivakirja);
        toolBarYhteenVeto.add(jSeparator2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelHenkiloValinta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paneeliEnergiaLaskuri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(toolBarYhteenVeto, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelToteutumaYhtVeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolBarYhteenVeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelHenkiloValinta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneeliEnergiaLaskuri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelToteutumaYhtVeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textHuomautusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHuomautusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHuomautusActionPerformed

    private void comboValitseHenkiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboValitseHenkiloActionPerformed
     /** Ladataan mahdollisesti muuttuneet tiedot levyltä. */ 
     tuotteet=Levytoiminta.lueTuotteet(tuotetietokanta); 
     tapahtumat=Levytoiminta.lueTapahtumat(tapahtumatietokanta); 
     henkilot=Levytoiminta.lueHenkilot(henkilotietokanta);  
     LinkedList<Double> henkilonPainot = new LinkedList<Double>(); // luetaan painodatat per henkilö //         
     LinkedList henkilonPunnituspaivat = new LinkedList<>(); //punnituspäivät esim trendiä varten //
     LinkedList henkilonEnergiat = new LinkedList<>(); //energiat esim trendiä varten //
     LinkedList henkilonProteiinit = new LinkedList<>();
     LinkedList henkilonHiilihydraatit = new LinkedList<>();
     LinkedList henkilonRasvat = new LinkedList<>();
     // Varmasti olisi parempiakin tapoja käsitellä tietoa, mutta en keksinyt tähän hätään //
     LinkedList henkilonEnergiatEdVrk = new LinkedList<>(); //edellisen vuorokauden energiat //
     LinkedList henkilonProteiinitEdVrk = new LinkedList<>();
     LinkedList henkilonHiilihydraatitEdVrk = new LinkedList<>();
     LinkedList henkilonRasvatEdVrk = new LinkedList<>();
     Double alkuPaino=0.0;
     String valinta = String.valueOf(comboValitseHenkilo.getSelectedItem());
      /** Pilkotaan teksti numeroon ja nimeen takaisin ja otetaan white space pois. */
        String[] valintaApu=valinta.split("\\s*-\\s*");
         /** valintaApu[0] = henkilönumero ja [1] on nimi. */         
        nimiApu=valintaApu[1]; // globaaliin muuttujaan
        henkiloNumeroApu=Integer.parseInt(valintaApu[0]); //globaaliin muuttujaan
          for (Henkilo e: henkilot) {
           if (Objects.equals(e.getHenkiloNumero(), henkiloNumeroApu)){
             //asetellaan kenttiin tiedot //
             textIka.setText(String.valueOf(e.getIka()));
             // alkupaino muuttujassa myöhempää laskentaa varten //
             alkuPaino=e.getPaino();
             textPaino.setText(String.valueOf(alkuPaino));
             textPituus.setText(String.valueOf(e.getPituus()));
             textHuomautus.setText(e.getHuomautus());
             DecimalFormat df=new DecimalFormat("0");
             String tekstiBMRin = df.format(Energia.ennusteBMR(e.getPaino(), 
                     e.getPituus(), e.getIka(), e.getSukupuoli()));
             textBMR.setText(tekstiBMRin);
             String tekstiYhteensaEnergiaIn = df.format(Energia.ennusteKokonaisKulutus(e.getPaino(), e.getPituus(), 
                             e.getIka(),e.getSukupuoli(), e.getAktiivisuus()));
             textYhteensaEnergia.setText(tekstiYhteensaEnergiaIn);
             // Relaatio Tapahtumatietokannan ja Henkilöiden välillä //
             for (Tapahtuma o: tapahtumat) {
                 // ... jos tapahtuma liittyy henkilöön ... //
                 if (Objects.equals(henkiloNumeroApu, o.getHenkilonumero())) {
                     txtEdellinenMitattuPaino.setText(String.valueOf(o.getPaino()));
                     // For ensimmäinen ja viimeinen tapahtuma
                      for (int i=0;i<tapahtumat.size();i++) {
                             // lisätään jokaisesta tapahtumasta muuttunut paino linkedlistaan //
                             // painotietoa voisi käyttää trendikuvaajan luomiseen //
                             henkilonPainot.add(o.getPaino());
                             // punnituspäivämäärät //
                             henkilonPunnituspaivat.add(o.getPaivamaara());
                             // energiat //
                             Double syotyMaara = o.getSyotymaara();
                            } //for i eli tapahtumat
                         } //if henkilöä vastaavat tiedot 
                      } //for tapahtuma
                 } //if HlöNumeron relaatio
             } //forTapahtumat
          // Päivitetään näkymään tietoja //
          txtEnsimmainenPunnitusPvm.setText(String.valueOf(henkilonPunnituspaivat.getFirst()));
          txtViimeisinPunnitusPvm.setText(String.valueOf(henkilonPunnituspaivat.getLast()));
          txtPainoEro.setText(String.valueOf(alkuPaino-henkilonPainot.getLast()));
          // Ennustepainon laskenta //
         try {
        // päiviä kulunut-tieto ... ihan himppasen konversiota sinne tänne :)
        Double paiviaKulunut = Double.parseDouble(String.valueOf(PaivaLaskuri.stringPaivaero(String.valueOf(henkilonPunnituspaivat.getFirst())
             , String.valueOf(henkilonPunnituspaivat.getLast()))));
        txtEnergiaPaiviaKulunut.setText(String.valueOf(PaivaLaskuri.stringPaivaero(String.valueOf(henkilonPunnituspaivat.getFirst())
             , String.valueOf(henkilonPunnituspaivat.getLast()))));
        // Energia, proteiini, HH ja rasvat yhteensä laskurit //
        // Relaatio gtin tapahtumat <-> tuotteet välillä //
        for (Tapahtuma u: tapahtumat) {
            // jos tapahtuman henkilönumero täsmää, toimi näin //
            if (Objects.equals(u.getHenkilonumero(), henkiloNumeroApu)) {
               // käydään tuotteet läpi ja etsitään syöty tuote * määrä // 
             for (Tuote t: tuotteet) {
                 //tuoterelaatio //
                if (Objects.equals(u.getGtin(), t.getGtin())) {
                    henkilonEnergiat.add(t.getEnergia()*u.getSyotymaara());
                    henkilonProteiinit.add(t.getProteiini()*u.getSyotymaara());
                    henkilonHiilihydraatit.add(t.getHiilihydraatti()*u.getSyotymaara());
                    henkilonRasvat.add(t.getRasva()*u.getSyotymaara());
                } //if ugting
             } //for t
            } //if henkilonumero   
        } //for u     
        
        // KCAL, prot, HH ja rasva syöty edellinen vrk //
        // edellinen vrk = tämä vuorkausi - 1 - String//
        Date tamaVrk = new Date();
        String edellinenVrk = PaivaLaskuri.poistaPaivia(tamaVrk, 1);
        // Tietokannassa sekä String-arvoiset että Date-arvoiset vrkt //
        for (Tapahtuma u: tapahtumat) {
            // jos tapahtuman henkilönumero ja päivämäärä täsmää, toimi näin //
            if (Objects.equals(u.getHenkilonumero(), henkiloNumeroApu) && 
               (edellinenVrk == null ? u.getPaivamaara() == null : edellinenVrk.equals(u.getPaivamaara()))) {
                 // käydään tuotteet läpi ja etsitään syöty tuote * määrä // 
               for (Tuote t: tuotteet) {
                 //tuoterelaatio //
                if (Objects.equals(u.getGtin(), t.getGtin())) {
                    henkilonEnergiatEdVrk.add(t.getEnergia()*u.getSyotymaara());
                    henkilonProteiinitEdVrk.add(t.getProteiini()*u.getSyotymaara());
                    henkilonHiilihydraatitEdVrk.add(t.getHiilihydraatti()*u.getSyotymaara());
                    henkilonRasvatEdVrk.add(t.getRasva()*u.getSyotymaara());
                } //if ugting
             } //for t
            } //if
        } //for U
         // KCAL, prot, HH ja rasva syöty edellinen vrk //
        Double energiatEdVrk=0.0; 
        for (int i=0;i<henkilonEnergiatEdVrk.size();i++) {
        energiatEdVrk = energiatEdVrk + Double.parseDouble(henkilonEnergiatEdVrk.get(i).toString());
        } //for
        Double proteiinitEdVrk=0.0; 
        for (int i=0;i<henkilonProteiinitEdVrk.size();i++) {
        proteiinitEdVrk = proteiinitEdVrk + Double.parseDouble(henkilonProteiinitEdVrk.get(i).toString());
        } //for
        Double hiilihydraatitEdVrk=0.0; 
        for (int i=0;i<henkilonHiilihydraatitEdVrk.size();i++) {
        hiilihydraatitEdVrk = hiilihydraatitEdVrk + Double.parseDouble(henkilonHiilihydraatitEdVrk.get(i).toString());
        } //for
        Double rasvatEdVrk=0.0; 
        for (int i=0;i<henkilonRasvatEdVrk.size();i++) {
        rasvatEdVrk = rasvatEdVrk + Double.parseDouble(henkilonRasvatEdVrk.get(i).toString());
        } //for
        // Päivitetään näkymään edellä lasketut tiedot //
        DecimalFormat df=new DecimalFormat("0");
        txtEnergiaEdVrk.setText(String.valueOf(df.format(energiatEdVrk)));
        textProtEdVrk.setText(String.valueOf(df.format(proteiinitEdVrk)));
        txtHHVrk.setText(String.valueOf(df.format(hiilihydraatitEdVrk)));
        txtRasvaVrk.setText(String.valueOf(df.format(rasvatEdVrk)));
               
        // KCAL, prot, HH ja rasva syöty koko aikana //
        Double energiatYht=0.0; 
        for (int i=0;i<henkilonEnergiat.size();i++) {
        energiatYht = energiatYht + Double.parseDouble(henkilonEnergiat.get(i).toString());
        } //for
        txtEnergiaKaikkiYht.setText(String.valueOf(df.format(energiatYht)));
        Double protskutYht=0.0;
        for (int i=0;i<henkilonProteiinit.size();i++) {
        protskutYht = protskutYht + Double.parseDouble(henkilonProteiinit.get(i).toString());
        } //for
        txtProtYht.setText(String.valueOf(df.format(protskutYht)));
        Double hiilaritYht=0.0;
        for (int i=0;i<henkilonHiilihydraatit.size();i++) {
        hiilaritYht = hiilaritYht + Double.parseDouble(henkilonHiilihydraatit.get(i).toString());
        } //for
        txtHHYht.setText(String.valueOf(df.format(hiilaritYht)));
        Double rasvatYht=0.0;
        for (int i=0;i<henkilonRasvat.size();i++) {
        rasvatYht = rasvatYht + Double.parseDouble(henkilonRasvat.get(i).toString());
        } //for
        txtRasvaYht.setText(String.valueOf(df.format(rasvatYht)));
       // Keskimäärin KCAL, prot, HH ja rasva per päivä
        txtEnergiaKeskimPaiva.setText(String.valueOf(df.format(energiatYht/paiviaKulunut)));
        txtProtKeskimPaiva.setText(String.valueOf(df.format(protskutYht/paiviaKulunut)));
        txtHHKeskimPaiva.setText(String.valueOf(df.format(hiilaritYht/paiviaKulunut)));
        txtRasvaKeskimPaiva.setText(String.valueOf(df.format(rasvatYht/paiviaKulunut)));
      // Ennustepaino on päivät edeltä, sinä aikana syöty energia - WHO ennuste / 7000 kcal per läskikilo //
       Double ennusteKokonaisEnergiaMaara=0.0;
       for (Henkilo h: henkilot) {
          if (Objects.equals(h.getHenkiloNumero(), henkiloNumeroApu)) {
             ennusteKokonaisEnergiaMaara = paiviaKulunut*Energia.ennusteKokonaisKulutus(
                    henkilonPainot.getLast(), h.getPituus(),h.getIka(),h.getSukupuoli(),h.getAktiivisuus());
         } //if
        } //for h
        // montako päivää kulunut //
        // Energia-ero, joka jaetaan läskikilon sisältämällä energiamäärälä //
        Double energiaErotus = energiatYht - ennusteKokonaisEnergiaMaara;
        Double painoEnnuste = energiaErotus/7000;
        DecimalFormat uf=new DecimalFormat("0.0");
        txtEnnusteEnergiaKok.setText(String.valueOf(df.format(ennusteKokonaisEnergiaMaara)));
        txtEnnustePainonAlentuminen.setText(String.valueOf(uf.format(painoEnnuste)));
        txtEnnustePaino.setText(String.valueOf(uf.format(henkilonPainot.getLast()+painoEnnuste)));
        // Tapahtumia yhteensä //
        txtEnergiaTapahtumiaYhteensa.setText(String.valueOf(henkilonEnergiat.size()));
        // Päivitetään eniten energiaa näkymää //
        listaEnitenSyodyt.setListData(enitenEnergiaa());
    } catch (ParseException ex) {
        Logger.getLogger(Yhteenveto.class.getName()).log(Level.SEVERE, null, ex);
    } //catch
     
    }//GEN-LAST:event_comboValitseHenkiloActionPerformed

    private void txtPainoEroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPainoEroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPainoEroActionPerformed

    private void buttonLopetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLopetaMouseClicked
        System.exit(0);
    }//GEN-LAST:event_buttonLopetaMouseClicked

    private void buttonHenkilotiedotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHenkilotiedotMouseClicked
        new HenkiloTiedot().setVisible(true);
    }//GEN-LAST:event_buttonHenkilotiedotMouseClicked

    private void buttonTuoteTiedotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTuoteTiedotMouseClicked
        new Tuotetiedot().setVisible(true);
    }//GEN-LAST:event_buttonTuoteTiedotMouseClicked

    private void buttonPaivakirjaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPaivakirjaMouseClicked
        new Paivakirja().setVisible(true);
    }//GEN-LAST:event_buttonPaivakirjaMouseClicked
    /**  @return Metodi listaa henkilönimen ja numeron.  */
    public static String[] listaaHenkiloNimet () {
     String[] henkiloNimet = new String[henkilot.size()];   
     int laskuri=0;
     for (int i=0;i<henkilot.size();i++) {
         if (henkilot.get(i).getOnkoAktiivinen()==true) {
             henkiloNimet[laskuri] = (henkilot.get(i).getHenkiloNumero()+
                     " - "+(henkilot.get(i).getNimi()));
             laskuri++; } //if
         } //for
    // kopioidaan uuteen tauluun ja tällä estetään tyhjien nimien ilmestyminen listaan//
     String[] henkiloNimetPalauta = new String[laskuri];   
     for (int i=0;i<laskuri;i++) {
         henkiloNimetPalauta[i]=henkiloNimet[i];
     } //for
    return henkiloNimetPalauta;     
    } //listaaHenkilot
    
    /**
     * Käy läpi syödyt ruoat ja mistä saatu eniten energiaa.
     * @return 10 eniten syödyn taulukon.
     */
    public static String[] enitenEnergiaa () {
     LinkedList tuotettaSyoty = new LinkedList <>();
     LinkedList energiaVertaa = new LinkedList<>();
     LinkedList<String> energiat = new LinkedList<String>();
     // vertailuarvon lähtöarvo //
     energiaVertaa.addFirst(Double.parseDouble(String.valueOf("0.0")));
     energiat.clear();
     // Relaatio tapahtumat - tuotenimet //
     for (Tapahtuma k: tapahtumat) {
         if (Objects.equals(k.getHenkilonumero(), henkiloNumeroApu)) {
             for (Tuote j: tuotteet) {
                if (Objects.equals(k.getGtin(), j.getGtin())) {
                     energiaVertaa.addFirst(k.getSyotymaara()*j.getEnergia());
                     for (int i=1;i<energiaVertaa.size();i++) {
                         // verrataan aina ensimmäiseen elementtiin, siksi addFirst //
                         if (Double.parseDouble(String.valueOf(energiaVertaa.get(0)))>Double.parseDouble(String.valueOf(energiaVertaa.get(i)))) {
                             //lisätään ensimmäinen elementti //
                              if (energiat.isEmpty()) {energiat.addFirst(k.getSyotymaara()*j.getEnergia()+" kcal / "+j.getTuoteNimi());}
                             } else if (energiat.size()>0) {
                               //tarkistetaan, ettei tuotetta ja ole listassa //
                                  for (int u=0;u<energiat.size();u++) {
                                     if (!onkoListassa(energiat, k.getSyotymaara()*j.getEnergia()+" kcal / "+j.getTuoteNimi()))  {
                                       energiat.add(k.getSyotymaara()*j.getEnergia()+" kcal / "+j.getTuoteNimi());
                                    } //if onko listassa
                                   } //for u
                            }  //else energian koko yli 0
                     } //for i
                }  //if tuoterelaatio
             } //for j
         } //if henkilörelaatio
     } //for k eli tapahtumat
     Collections.sort(energiat, Collections.reverseOrder());  
     
    // puretaan uuteen taulukkoon energianmukaisesti //
     String[] enitenEnergiaa = energiat.toArray(new String[energiat.size()]);  
     // mikäli lista kasvaa liian suureksi, järkevää katkoa jostain //
     return enitenEnergiaa;     
    } //enitenEnergiaa
        
    /**
     * Palauttaa totuusarvon siitä, esiintyykö merkkijono listassa.
     * @param lista sisääntule lista.
     * @param merkkijono vertailtava merkkijono.
     * @return totuusarvo esiintyvyydestä.
     */
    public static boolean onkoListassa (LinkedList lista, String merkkijono) {
    for (int i=0;i<lista.size();i++) {
    if (lista.get(i).equals(merkkijono)) {
        return true;  
     } //if  
    } //for
    return false;   
}

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHenkilotiedot;
    private javax.swing.JButton buttonLopeta;
    private javax.swing.JButton buttonPaivakirja;
    private javax.swing.JButton buttonTuoteTiedot;
    private javax.swing.JComboBox<String> comboValitseHenkilo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JLabel labelBMR;
    private javax.swing.JLabel labelEnergiaEdellinenVRK;
    private javax.swing.JLabel labelEnergiaKaikkiYhteensa;
    private javax.swing.JLabel labelEnergiaPaiva;
    private javax.swing.JLabel labelEnergiaTapahtumiaYht;
    private javax.swing.JLabel labelEnnsutePainoAlennus;
    private javax.swing.JLabel labelEnnusteEnergiaKok;
    private javax.swing.JLabel labelEnnustepaino;
    private javax.swing.JLabel labelEnsimmainenPunnitusvm;
    private javax.swing.JLabel labelHiilaria;
    private javax.swing.JLabel labelHuomautus;
    private javax.swing.JLabel labelIka;
    private javax.swing.JLabel labelKCALSyoty;
    private javax.swing.JLabel labelKeskimPaiva;
    private javax.swing.JLabel labelLaskennalliset;
    private javax.swing.JLabel labelMitattuPainoEdellinen;
    private javax.swing.JLabel labelPaino;
    private javax.swing.JLabel labelPainoEro;
    private javax.swing.JLabel labelPituus;
    private javax.swing.JLabel labelProteiinia;
    private javax.swing.JLabel labelRasvaa;
    private javax.swing.JLabel labelViimeisinPunnitusPvm;
    private javax.swing.JList<String> listaEnitenSyodyt;
    private javax.swing.JPanel paneeliEnergiaLaskuri;
    private javax.swing.JPanel panelHenkiloValinta;
    private javax.swing.JPanel panelToteutumaYhtVeto;
    private javax.swing.JScrollPane scrollYhteenveto;
    private javax.swing.JTextField textBMR;
    private javax.swing.JTextField textHuomautus;
    private javax.swing.JTextField textIka;
    private javax.swing.JTextField textPaino;
    private javax.swing.JTextField textPituus;
    private javax.swing.JTextField textProtEdVrk;
    private javax.swing.JTextField textYhteensaEnergia;
    private javax.swing.JToolBar toolBarYhteenVeto;
    private javax.swing.JTextField txtEdellinenMitattuPaino;
    private javax.swing.JTextField txtEnergiaEdVrk;
    private javax.swing.JTextField txtEnergiaKaikkiYht;
    private javax.swing.JTextField txtEnergiaKeskimPaiva;
    private javax.swing.JTextField txtEnergiaPaiviaKulunut;
    private javax.swing.JTextField txtEnergiaTapahtumiaYhteensa;
    private javax.swing.JTextField txtEnnusteEnergiaKok;
    private javax.swing.JTextField txtEnnustePaino;
    private javax.swing.JTextField txtEnnustePainonAlentuminen;
    private javax.swing.JTextField txtEnsimmainenPunnitusPvm;
    private javax.swing.JTextField txtHHKeskimPaiva;
    private javax.swing.JTextField txtHHVrk;
    private javax.swing.JTextField txtHHYht;
    private javax.swing.JTextField txtPainoEro;
    private javax.swing.JTextField txtProtKeskimPaiva;
    private javax.swing.JTextField txtProtYht;
    private javax.swing.JTextField txtRasvaKeskimPaiva;
    private javax.swing.JTextField txtRasvaVrk;
    private javax.swing.JTextField txtRasvaYht;
    private javax.swing.JTextField txtViimeisinPunnitusPvm;
    // End of variables declaration//GEN-END:variables
}
